# Generated by Django 2.0 on 2018-09-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bind', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordinvite',
            name='groups',
        ),
        migrations.DeleteModel(
            name='DiscordInvite',
        ),
    ]
